all:
	clang -o ProLang.out lexer.c cli.c -I ../include
debug:
	clang -g lexer.c cli.c -I ../include
gcc:
	clang -o ProLang.out lexer.c cli.c -I ../include
help:
	echo -n Available options: debug, clang, gcc, all, help
