all:
	gcc -o ProLang.out lexer.c cli.c -I ../include
debug:
	gcc -g lexer.c cli.c -I ../include
clang:
	clang -o ProLang.out lexer.c cli.c -I ../include
gcc:
	gcc -o ProLang.out lexer.c cli.c -I ../include
help:
	echo -n Available options: debug, clang, gcc, all, help
